

export const properties = [
  {
    id: 1,
    cover: "../images/PropertyImages/property2.jpg",
    name: "Ashoka Hotel",
    location: "Delhi",
    category: "FOR RENTAL SALE",
    price: "3700",
    type: "Hotel",
    beds: 4,
    date: "2022-11-01",
    bathrooms: 2,
    area: "5*7m²",
  },
  {
    id: 2,
    cover: "../images/PropertyImages/property1.jpg",
    name: "Fairmount Properties",
    location: "Mumbai",
    category: "FIXED SALE",
    price: "9750",
    type: "Houses",
    beds: 4,
    date: "2022-11-01",
    bathrooms: 3,
    area: "2*7m²",
  },
  {
    id: 3,
    cover: "../images/PropertyImages/property3.jpg",
    name: "The Real Estate Corner",
    location: "Gurgaon",
    category: "FOR RENTAL SALE",
    price: "5860",
    type: "Flats",
    beds: 4,
    date: "2022-11-01",
    bathrooms: 3,
    area: "3*7m²",
  },
  {
    id: 4,
    cover: "../images/PropertyImages/property4.jpg",
    name: "Herringbone Realty",
    location: "Chennai",
    category: "FIXED SALE",
    price: "7540",
    type: "Rooms",
    beds: 4,
    date: "2022-11-17",
    bathrooms: 3,
    area: "4*7m²",
  },
  {
    id: 5,
    cover: "../images/PropertyImages/property5.jpg",
    name: "Aastha Valley",
    location: "Delhi",
    category: "FOR RENTAL SALE",
    price: "4850",
    type: "Offices",
    beds: 4,
    date: "2022-11-18",
    bathrooms: 3,
    area: "5*7m²",
  },
  {
    id: 6,
    cover: "../images/PropertyImages/property1.jpg",
    name: "Banyon Tree Realty",
    location: "Mumbai",
    category: "FIXED SALE",
    price: "2742",
    type: "Apartment",
    beds: 4,
    date: "2022-11-24",
    bathrooms: 3,
    area: "6*7m²",
  },
  {
    id: 7,
    cover: "../images/PropertyImages/property2.jpg",
    name: "Shyam Towers",
    location: "Gurgaon",
    category: "FIXED SALE",
    price: "2742",
    type: "Hotel",
    beds: 4,
    date: "2022-11-01",
    bathrooms: 3,
    area: "5*7m²",
  },
  {
    id: 8,
    cover: "../images/PropertyImages/property3.jpg",
    name: "Hello Buildings",
    location: "Chennai",
    category: "FIXED SALE",
    price: "2742",
    type: "Apartment",
    beds: 3,
    date: "2022-11-20",
    bathrooms: 2,
    area: "5*7m²",
  },
  {
    id: 9,
    cover: "../images/PropertyImages/property4.jpg",
    name: "Kamal Buildings",
    location: "Chennai",
    category: "FIXED SALE",
    price: "2742",
    type: "Hotel",
    beds: 3,
    date: "2022-11-21",
    bathrooms: 2,
    area: "1*7m²",
  },
  {
    id: 10,
    cover: "../images/PropertyImages/property5.jpg",
    name: "Palak Buildings",
    location: "Delhi",
    category: "FIXED SALE",
    price: "6000",
    type: "Offices",
    beds: 4,
    date: "2022-11-23",
    bathrooms: 3,
    area: "6*7m²",
  },
  {
    id: 11,
    cover: "../images/PropertyImages/property1.jpg",
    name: "Gandhar Apartments",
    location: "Mumbai",
    category: "FIXED SALE",
    price: "9999",
    type: "Hotel",
    beds: 4,
    date: "2022-11-25",
    bathrooms: 3,
    area: "5*7m²",
  },
  {
    id: 12,
    cover: "../images/PropertyImages/property2.jpg",
    name: "Hiranandani Niwas",
    location: "Gurgaon",
    category: "FIXED SALE",
    price: "2000",
    type: "Houses",
    beds: 4,
    date: "2022-11-01",
    bathrooms: 3,
    area: "50*70m²",
  },
  {
    id: 13,
    cover: "../images/PropertyImages/property3.jpg",
    name: "Tena Apartments",
    location: "Chennai",
    category: "FIXED SALE",
    price: "15000",
    type: "Houses",
    beds: 4,
    date: "2022-11-27",
    bathrooms: 3,
    area: "10*10m²",
  },
  {
    id: 14,
    cover: "../images/PropertyImages/property2.jpg",
    name: "Ghazi Villa",
    location: "Mumbai",
    category: "FIXED SALE",
    price: "2742",
    type: "Rooms",
    beds: 4,
    date: "2022-11-01",
    bathrooms: 3,
    area: "5*7m²",
  },
  {
    id: 15,
    cover: "../images/PropertyImages/property3.jpg",
    name: "Salman Apartments",
    location: "Delhi",
    category: "FIXED SALE",
    price: "3842",
    type: "Apartment",
    beds: 4,
    date: "2022-11-01",
    bathrooms: 3,
    area: "5*7m²",
  },
  {
    id: 16,
    cover: "../images/PropertyImages/property4.jpg",
    name: "Khan Rooms",
    location: "Mumbai",
    category: "FIXED SALE",
    price: "2742",
    type: "Rooms",
    beds: 4,
    date: "2022-11-01",
    bathrooms: 3,
    area: "5*7m²",
  },
  
 

];
